version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    # 1) install your package in editable mode, with the "docs" extras
    - method: pip
      path: .
      editable: true
      extra_requirements:
        - docs
    # 2) upgrade Sphinx itself in case you need the latest bugfixes
    - method: pip
      requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

submodules:
  include:
    - "docs/tutorials/notebooks"
  recursive: true
